# Generated by Django 4.2.7 on 2024-05-20 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Reg_no', models.CharField(max_length=50)),
                ('Name', models.CharField(max_length=100)),
                ('fathers_name', models.CharField(max_length=100)),
                ('center_name', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=40)),
                ('grade', models.CharField(max_length=100)),
                ('passing_year', models.CharField(max_length=100)),
                ('Certificate_no', models.CharField(blank=True, max_length=100, null=True)),
                ('Batch', models.CharField(blank=True, max_length=50, null=True)),
                ('Issued_date', models.DateField()),
                ('Certificate', models.ImageField(blank=True, null=True, upload_to='certificates/')),
            ],
        ),
    ]
