# Generated by Django 4.2.7 on 2024-05-20 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_data_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
